language: cpp

os: linux
dist: focal

jobs:
   include:
      - env: DB=dynamo FS=s3
        arch: arm64-graviton2
        compiler: gcc

branches:
    only:
        - main

cache: apt
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl-dev
      - uuid-dev
      - zlib1g-dev
      - libpulse-dev

before_install: 
    - cd ..
    - git clone https://github.com/aws/aws-sdk-cpp.git
    - mkdir aws-sdk-cpp.build && cd aws-sdk-cpp.build
    - cmake ../aws-sdk-cpp -DBUILD_ONLY="dynamodb;s3" -DENABLE_TESTING=OFF -DCUSTOM_MEMORY_MANAGEMENT=OFF  -DBUILD_SHARED_LIBS=OFF
    - sudo make && sudo make install
    - cd ..
    - git clone https://github.com/Thalhammer/jwt-cpp.git
    - mkdir jwt-cpp.build && cd jwt-cpp.build
    - cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ../jwt-cpp
    - make && sudo make install    
    - cd ..
    - git clone https://github.com/yhirose/cpp-httplib.git
    - mkdir httplib.build && cd httplib.build
    - cmake ../cpp-httplib 
    - make && sudo make install
    - cd ..
    - mkdir vts && mkdir vts.build && cd vts.build
    - cmake -DDB_MYSQL=ON -DDB_DYNAMO=OFF -DFS_S3=ON ../vitanza-service; fi
       
script: make -j4
